Add Schuelerzeitung
KlnSdr/website-1 pull request #1
Opened 2022-01-10 13:22 UTC by ileFixDev

2022-01-16 19:19 UTC, KlnSdr commented
Sorry. Habe es erst jetzt gesehen. Ich schaue gleich drüber.

2022-01-16 19:50 UTC, KlnSdr requested changes
Kannst du bitte noch die Artikelübersicht des Schülerrats einbinden? Den Menüpunkt unter Konto brauchst du nicht hinzuzufügen, dass wird automatisch gemacht, sobald die Berechtigung da ist.

2022-01-16 19:50 UTC, KlnSdr commented on src/public/public/preload.ts
> +                                <a href='/schuelerzeitung/allgemein'>Schülerzeitung</a>
falscher Link

2022-01-16 19:50 UTC, KlnSdr commented on src/public/public/preload.ts
> +                                        <li><a href='/schuelerzeitung/allgemein'>Allgemein</a></li>
falscher Link

2022-01-16 19:50 UTC, KlnSdr commented on src/public/schuelerzeitung/informationen/index.html
> +            <h6><b>Wer sind wir?</b></h6><br><br>
Die Überschriften passen nicht zusammen.

2022-01-16 19:50 UTC, KlnSdr commented on src/public/schuelerzeitung/informationen/index.html
> +                Ihr findet uns jeden Montag um 13:45 Uhr im Kellerraum 29. Auf Instagram könnt ihr uns unter folgendem Namen finden: provokant4u Schreibt uns sonst auch gerne eine E-Mail: schuelerzei
Die Mail eventuell mit `<a href="mailto:...">some Text</a>`

2022-01-16 19:50 UTC, KlnSdr commented on src/public/schuelerzeitung/informationen/index.html
> +                <h2>Willkommen zur <b>Allgemeinen Vorstellung</b> der</h2>
Vielleicht nur "Vorstellung"

2022-01-16 19:50 UTC, KlnSdr commented on src/public/public/preload.ts
> -                                        </li>
sollte eventuell drinnen bleiben

2022-01-17 13:37 UTC, ileFixDev commented
Was meinst du für eine Artikelübersicht?

2022-01-17 15:30 UTC, KlnSdr commented
Das hier: https://kant-schulleben.de/schuelerrat/aktuelles/

2022-01-17 17:35 UTC, ileFixDev reviewed
accept changes

2022-01-17 17:45 UTC, ileFixDev commented on src/public/schuelerzeitung/informationen/index.html
> +            <h6><b>Wer sind wir?</b></h6><br><br>
Welche genau?

2022-01-17 17:54 UTC, ileFixDev commented
Den aktuelles Tab müsstest doch du mal schnell Einfügen bitte. Ich hab nicht 100% den Überblick da, was ich wo einfügen + ändern muss.

2022-01-23 16:38 UTC, merged